// COUNTER ACTION TYPES
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const IS_LOADING = 'IS_LOADING';

export const UPDATE_CURRENT_MOVIE = 'UPDATE_CURRENT_MOVIE';

export const UPDATE_DOCUMENT_TITLE = 'UPDATE_DOCUMENT_TITLE';
